name: dhakarni_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.0
  permission_handler: ^11.3.1
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  firebase_auth: ^5.7.0
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.1.0
  intl: ^0.20.2
  provider: ^6.1.1
  shared_preferences: ^2.2.0
  firebase_database: ^11.3.10
  get: ^4.6.5
  firebase_dynamic_links: ^6.1.10
  image_picker: ^1.1.0
  file_picker: ^10.3.2
  path_provider: ^2.1.3
  firebase_storage: ^12.4.10
  font_awesome_flutter: ^10.7.0
  uuid: ^4.2.1
  url_launcher: ^6.1.10
  cached_network_image: ^3.3.0
  share_plus: ^11.1.0
  cloudinary_public: ^0.23.1
  http: ^1.1.0
  path: ^1.8.3
  open_filex: ^4.3.2
  flutter_image_compress: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: ^2.3.1
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/app.png"
  min_sdk_android: 21

flutter_native_splash:
  background_image: "assets/splash_background.png"
  color: "#FCE4EC"
  image: "assets/splash_logo.png"
  android_gravity: center
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/person_with_phone.png
    - assets/Man-With-Phone.png
    - assets/dhakarni_logo.png
    - assets/man.png
    - assets/building1.png
    - assets/Group26887.png
    - assets/Notifchat.png
    - assets/12-janv.png
    - assets/22-avril.png
    - assets/AppleIphone.png
    - assets/email_sent.png
    - assets/warranty_success_icon.png
    - assets/Email sent.png
    - assets/not-found.png
    - assets/notif.png
    - assets/migration.png
    - assets/profile_completion_icon.png